// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608151909_AdjustDecimalPrecision")]
    partial class AdjustDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 447, DateTimeKind.Utc).AddTicks(2028),
                            IsDeleted = false,
                            Name = "Saygıner and Sons"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 452, DateTimeKind.Utc).AddTicks(5616),
                            IsDeleted = false,
                            Name = "Yeşilkaya - Orbay"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 452, DateTimeKind.Utc).AddTicks(7765),
                            IsDeleted = false,
                            Name = "Babaoğlu, Poyrazoğlu and Özkara"
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 414, DateTimeKind.Utc).AddTicks(3566),
                            IsDeleted = false,
                            Name = "Music",
                            ParentId = 0,
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 415, DateTimeKind.Utc).AddTicks(7947),
                            IsDeleted = false,
                            Name = "Grocery",
                            ParentId = 0,
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 415, DateTimeKind.Utc).AddTicks(8007),
                            IsDeleted = false,
                            Name = "Beauty",
                            ParentId = 1,
                            Priority = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 415, DateTimeKind.Utc).AddTicks(8012),
                            IsDeleted = false,
                            Name = "Jewelery",
                            ParentId = 2,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 422, DateTimeKind.Utc).AddTicks(6636),
                            Description = "Ki sit sed değirmeni. Mutlu adanaya sed quae aperiam sıla. Telefonu ab quae molestiae umut eos. Numquam beğendim de beğendim.",
                            IsDeleted = false,
                            Title = "Adresini laudantium consequatur."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 437, DateTimeKind.Utc).AddTicks(8665),
                            Description = "Veritatis ad dolores hesap sit anlamsız ekşili mi. Gülüyorum qui gülüyorum koyun vel magni esse. Quae suscipit et exercitationem cezbelendi.",
                            IsDeleted = false,
                            Title = "Cezbelendi sıla nesciunt."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 437, DateTimeKind.Utc).AddTicks(9030),
                            Description = "Bilgiyasayarı umut beatae. Çünkü ve esse tempora numquam commodi. Et sıfat sit umut bilgiyasayarı teldeki et minima dolore sed. Minima sequi sarmal. Consequuntur sevindi rem dağılımı commodi laboriosam perferendis cezbelendi.",
                            IsDeleted = false,
                            Title = "Ötekinden voluptatem bahar."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 437, DateTimeKind.Utc).AddTicks(9165),
                            Description = "Totam sed yapacakmış lakin. Işık quaerat enim eve dolore labore dicta rem ötekinden odit.",
                            IsDeleted = false,
                            Title = "Veniam sed adanaya."
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 441, DateTimeKind.Utc).AddTicks(6723),
                            Description = "Sıla göze aut praesentium minima aliquam vitae. Voluptatem quis sokaklarda biber esse dergi exercitationem şafak et. Sit quia aperiam dicta quis ipsum fugit. Suscipit esse lakin iusto sokaklarda oldular molestiae.",
                            Discount = 44.51m,
                            IsDeleted = false,
                            Price = 474.39m,
                            Title = "Unbranded Frozen Chair"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 445, DateTimeKind.Utc).AddTicks(649),
                            Description = "Quia dicta veritatis. Çıktılar et numquam beğendim kalemi yazın ut ab voluptatem. Sıradanlıktan eaque ut voluptatem sokaklarda bahar beğendim bundan sokaklarda vel. Corporis cezbelendi ve praesentium sit iure voluptatem corporis. Gül sıfat masaya dışarı koyun de.",
                            Discount = 43.30m,
                            IsDeleted = false,
                            Price = 440.07m,
                            Title = "Intelligent Granite Fish"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 445, DateTimeKind.Utc).AddTicks(995),
                            Description = "Kapının ut salladı tempora et numquam un amet iusto. Yazın gitti enim totam. Voluptatem eaque voluptatem laudantium biber sinema magnam explicabo sit bilgisayarı.",
                            Discount = 38.14m,
                            IsDeleted = false,
                            Price = 618.81m,
                            Title = "Licensed Wooden Shoes"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 19, 8, 445, DateTimeKind.Utc).AddTicks(1113),
                            Description = "Consectetur voluptatem dignissimos consectetur corporis. Tv quis mıknatıslı umut tempora bilgiyasayarı enim ab ona hesap. Sayfası nemo dolayı exercitationem ullam dolayı nemo sandalye. İçin magni ratione.",
                            Discount = 46.47m,
                            IsDeleted = false,
                            Price = 161.12m,
                            Title = "Handcrafted Steel Bike"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Core.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entities.Detail", b =>
                {
                    b.HasOne("Core.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("Core.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
