// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608151700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 944, DateTimeKind.Utc).AddTicks(8512),
                            IsDeleted = false,
                            Name = "Kunter - Aybar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 950, DateTimeKind.Utc).AddTicks(5262),
                            IsDeleted = false,
                            Name = "Kulaksızoğlu, Sarıoğlu and Tunçeri"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 950, DateTimeKind.Utc).AddTicks(5591),
                            IsDeleted = false,
                            Name = "Demirbaş Inc"
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 908, DateTimeKind.Utc).AddTicks(7055),
                            IsDeleted = false,
                            Name = "Games",
                            ParentId = 0,
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 910, DateTimeKind.Utc).AddTicks(286),
                            IsDeleted = false,
                            Name = "Computers",
                            ParentId = 0,
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 910, DateTimeKind.Utc).AddTicks(352),
                            IsDeleted = false,
                            Name = "Clothing",
                            ParentId = 1,
                            Priority = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 910, DateTimeKind.Utc).AddTicks(362),
                            IsDeleted = false,
                            Name = "Computers",
                            ParentId = 2,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 918, DateTimeKind.Utc).AddTicks(4102),
                            Description = "Vel sed camisi. Kalemi dolayı okuma gazete voluptatum.",
                            IsDeleted = false,
                            Title = "Un enim olduğu."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 934, DateTimeKind.Utc).AddTicks(1671),
                            Description = "Qui kulu iusto bundan ab et magnam beatae sed. İpsum minima consequatur doğru amet kutusu. Mutlu ipsam ea. Ona eius çıktılar non dicta et qui voluptatem mi gitti. Düşünüyor magni dicta ea çakıl türemiş ötekinden architecto architecto.",
                            IsDeleted = false,
                            Title = "Sayfası koştum ipsa."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 934, DateTimeKind.Utc).AddTicks(2227),
                            Description = "Explicabo karşıdakine et biber suscipit nemo açılmadan. Ut ducimus dicta velit laudantium laudantium illo okuma blanditiis modi. Totam ötekinden aliquid perferendis. Işık koşuyorlar nihil karşıdakine qui dışarı layıkıyla çarpan biber sinema. İncidunt nemo inventore ut düşünüyor dolayı adipisci layıkıyla gazete iure.",
                            IsDeleted = false,
                            Title = "De nemo ipsum."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 934, DateTimeKind.Utc).AddTicks(2530),
                            Description = "Ullam quia deleniti deleniti commodi değirmeni illo aliquam. Doğru ad bahar gidecekmiş quis bahar domates gül eve. Ullam commodi voluptatem sıfat. Sit ut deleniti olduğu oldular koşuyorlar incidunt amet dolayı.",
                            IsDeleted = false,
                            Title = "Işık un in."
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 938, DateTimeKind.Utc).AddTicks(2617),
                            Description = "İncidunt dağılımı aliquid ab. Voluptatem consequatur quam çarpan enim voluptatem quis sinema suscipit eos. Sed sit çobanın enim. Gülüyorum quia mıknatıslı filmini dignissimos dışarı masanın sandalye açılmadan. Qui karşıdakine esse velit iusto.",
                            Discount = 28.73m,
                            IsDeleted = false,
                            Price = 313.98m,
                            Title = "Licensed Plastic Chicken"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 941, DateTimeKind.Utc).AddTicks(9184),
                            Description = "Koştum ullam aut. Praesentium ki esse eaque et duyulmamış dolorem. Rem inventore tempora. Non çıktılar dolorem quia ona blanditiis.",
                            Discount = 54.75m,
                            IsDeleted = false,
                            Price = 503.77m,
                            Title = "Practical Granite Pants"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 941, DateTimeKind.Utc).AddTicks(9595),
                            Description = "Yazın çakıl corporis vitae sarmal uzattı quam balıkhaneye duyulmamış. Gülüyorum et nostrum mıknatıslı karşıdakine quis autem.",
                            Discount = 93.40m,
                            IsDeleted = false,
                            Price = 808.81m,
                            Title = "Small Cotton Bike"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 6, 8, 15, 16, 58, 941, DateTimeKind.Utc).AddTicks(9749),
                            Description = "Sinema ut orta. Masanın qui sandalye. Layıkıyla iusto çorba consequatur çıktılar veniam.",
                            Discount = 45.39m,
                            IsDeleted = false,
                            Price = 956.52m,
                            Title = "Licensed Concrete Mouse"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Core.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entities.Detail", b =>
                {
                    b.HasOne("Core.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("Core.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
